server:
  port: 8081

file:
  upload-dir: upload/

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
    data: classpath:/sql/data.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
#    password:  # 비밀번호가 있으면 입력
#    timeout: 3000ms  # 연결 타임아웃 (기본 2000ms)
#    lettuce:
#      pool:
#        max-active: 8  # 최대 커넥션 개수
#        max-idle: 8  # 최대 유휴 커넥션 개수
#        min-idle: 0  # 최소 유휴 커넥션 개수
#        max-wait: 1000ms  # 커넥션 풀이 가득 찼을 때 대기 시간
#
logging:
  level:
    root: info